language: "perl"
perl:
  - "5.18"
  #- "5.14"
  #- "5.12"
  #- "5.8"

before_install:
    - cpanm IPC::ConcurrencyLimit --notest --mirror http://cpan.mirrors.travis-ci.org
    - cpanm Perl::Critic --notest --mirror http://cpan.mirrors.travis-ci.org
# - cpanm -n Devel::Cover::Report::Coveralls
# see http://search.cpan.org/~mikihoshi/Devel-Cover-Report-Coveralls-0.06/lib/Devel/Cover/Report/Coveralls.pm

# should really use dependency manager and --install-deps as below

#install:
#    - cpanm -v --installdeps --notest --mirror http://cpan.mirrors.travis-ci.org .

#script: "perl Build.PL; ./Build test"

script:
  - perl -c src/*.pl
  - perlcritic --brutal --verbose 5 t/
  - perlcritic --brutal --verbose 5 src/
  - prove

#branches:
#   only:
#     - master

notifications:
  email:
    on_success: change
    on_failure: always

#env:
